In [1]:
from dataclasses import dataclass
import torch
import torch.nn as nn
from torch.nn import functional as F

In [18]:
@dataclass
class mlpConfig:
    p: int
    n: int

class MLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.l1 = nn.Linear(in_features=config.p, out_features=1)
    
    def forward(self, x, targets):
        # x = self.l1(x)
        
        if targets is not None:
            preds = self.l1(x)
            loss = F.mse_loss(preds, targets)
        else:
            preds = self.l1(x)
            loss = F.mse_loss(preds, targets)
        
        return preds, loss

In [3]:
m = nn.Linear(20, 1)
input = torch.randn(128, 20)
output = m(input)
print(output.size())

torch.Size([128, 1])


In [4]:
print(input[0])
print(output[0])

tensor([ 0.5633,  0.2088,  0.7788,  2.4923,  2.1824,  1.9392, -0.4710, -0.0449,
         0.1375,  0.4414, -1.9891,  0.9475, -1.5108,  0.1192,  0.1026, -1.6008,
        -0.1441,  0.6229, -0.8541, -0.5330])
tensor([-0.8759], grad_fn=<SelectBackward0>)


In [ ]:
import pandas as pd

In [35]:
data = pd.read_csv("/Users/samswitz/GitHub/rthon/test_data/prostate.csv")
info = pd.read_csv("/Users/samswitz/GitHub/rthon/test_data/tidy_coefficients.csv")

In [36]:
data.head()

,lcavol,lweight,age,lbph,svi,lcp,gleason,pgg45,lpsa
0,-0.579819,2.7695,50,-1.386294,0,-1.38629,6,0,-0.43078
1,-0.994252,3.3196,58,-1.386294,0,-1.38629,6,0,-0.16252
2,-0.510826,2.6912,74,-1.386294,0,-1.38629,7,20,-0.16252
3,-1.203973,3.2828,58,-1.386294,0,-1.38629,6,0,-0.16252
4,0.751416,3.4324,62,-1.386294,0,-1.38629,6,0,0.37156


In [38]:
data.iloc[:,-1].values

array([-0.43078, -0.16252, -0.16252, -0.16252,  0.37156,  0.76547,
        0.76547,  0.85442,  1.04732,  1.04732,  1.26695,  1.26695,
        1.26695,  1.34807,  1.39872,  1.44692,  1.47018,  1.4929 ,
        1.55814,  1.59939,  1.639  ,  1.65823,  1.69562,  1.7138 ,
        1.73166,  1.76644,  1.80006,  1.81645,  1.84845,  1.89462,
        1.92425,  2.00821,  2.00821,  2.02155,  2.04769,  2.08567,
        2.15756,  2.19165,  2.21375,  2.27727,  2.29757,  2.30757,
        2.32728,  2.37491,  2.52172,  2.55334,  2.56879,  2.56879,
        2.59152,  2.59152,  2.65676,  2.67759,  2.68444,  2.69124,
        2.70471,  2.718  ,  2.78809,  2.79423,  2.80639,  2.81241,
        2.842  ,  2.85359,  2.85359,  2.882  ,  2.882  ,  2.88759,
        2.92047,  2.96269,  2.96269,  2.97298,  3.01308,  3.03735,
        3.05636,  3.07501,  3.27526,  3.33755,  3.39283,  3.4356 ,
        3.45789,  3.51304,  3.51601,  3.53076,  3.5653 ,  3.57094,
        3.58768,  3.63099,  3.68009,  3.71235,  3.98434,  3.99

In [49]:
X = torch.tensor(data.iloc[:,:8].values, dtype=torch.float)
y = torch.tensor(data.iloc[:,-1].values, dtype=torch.float).view(y.shape[0], -1)

# print(y)

In [40]:
config = mlpConfig(p=X.shape[1], n=X.shape[0])
model = MLP(config)

In [57]:
logits, loss = model(X, y)

In [59]:
logits

tensor([[ 1.8854],
        [ 2.5391],
        [ 4.6867],
        [ 2.5008],
        [ 3.1577],
        [ 1.8686],
        [ 4.0153],
        [ 3.8478],
        [ 1.7080],
        [ 3.1305],
        [ 3.3438],
        [ 3.8419],
        [ 4.6611],
        [ 3.6007],
        [ 2.6840],
        [ 3.5619],
        [ 5.8776],
        [ 3.5407],
        [ 1.2203],
        [ 4.8194],
        [ 2.9756],
        [ 4.7174],
        [ 2.9026],
        [ 6.9043],
        [ 4.7302],
        [ 4.3005],
        [ 7.0921],
        [ 5.3924],
        [ 8.2995],
        [ 3.2911],
        [ 4.4966],
        [ 4.7193],
        [ 4.8401],
        [ 2.3681],
        [ 3.0177],
        [ 4.7027],
        [ 4.3362],
        [ 3.6974],
        [ 5.9901],
        [ 3.2532],
        [ 6.6534],
        [ 4.0548],
        [ 4.1406],
        [ 3.0634],
        [ 5.4146],
        [ 4.4682],
        [10.1144],
        [ 6.7584],
        [ 1.7813],
        [ 4.7825],
        [ 6.3697],
        [ 4.7639],
        [ 7.